### ISSUE TITLE
16x17 I can't paint in the bottom row.

### ISSUE THREAD

**Issue by remy** [remy/zx-tools#11]
> I get the same behaviour when I start from scratch, using your default 16x12 map. If I change it to 16x17 I can't paint in the bottom row.  I think you're doing a y bounds check but using the x value instead 🙂.

**Comment by Duefectu** [comment]
This mornig I see that bug is fixed, but it's not to easy to work in this way.
I changed div "tile-map-container" height to a lower size and I can work in a very good way with the scrollbars.

**Comment by remy** [comment]
Oh, was this simply hidden in the overflow? (on a mac the damn scrollbars are hidden unless you move, which is a pain - I might see if there's a way I can force these to show).

**Comment by remy** [comment]
No, nm - I can replicate this bug. Load: resize to 16x17, try to paint bottom row - no effect.

**Comment by remy** [comment]
This is fixed and live now.

**Comment by celeritydesign** [comment]
Sorry @remy - this was fixed but has resurfaced in latest version.
Tested in incognito tab in Chrome:
- set up 5x6 map
- try and paste tile in 6th (bottom) row - tile will not paint, and actually appears in osition 0,0 as you mouseover row 6.

**Comment by remy** [comment]
Sod - I remember reading this but couldn't find _where_ I read it. 

I've reopened and investigate.

**Comment by remy** [comment]
Fix being deployed now - thanks again for the report.
