### ISSUE TITLE
Request: Color droper in sprite editor

### ISSUE THREAD

**Issue by Duefectu** [remy/zx-tools#13]
Your project is awesome!!!
As a suggestion: A color droper for sprite editor.
It's very hard to retouch sprites without this tool.

**Comment by remy** [comment]
It does mention it in the [usage](https://zx.remysharp.com/sprites/#usage) for the sprite tool - it's alt+click anywhere on the canvas.

Happy to reopen if I misunderstood.

**Comment by Duefectu** [comment]
The "add to the palette" in the help has confused me, but now I undertand!

**Comment by remy** [comment]
Yeah, I can understand that. I'm thinking of how I can surface that
particular interaction as you're not the first to miss it 👍
