### ISSUE TITLE
Request: Tilemap: wider or resizeable UI 

### ISSUE THREAD

**Issue by celeritydesign** [remy/zx-tools#15]
The map viewer only utilises about 40% of my screen width. Would it be possible to make the UI more responsive to expand as needed to fill available screen width?
I'd suggest the Map Settings area to the right could be moved out of the main area, perhaps as a new tab, as it generally isn't needed once painting starts. This would provide even more real estate to view larger world maps.

Cheers!

**Comment by remy** [comment]
Collapsing the settings is a good idea and will help take up more space. 

I've got a local copy that I'm working on (to add 8x8 tile support) that expands the map to use more space too:

<img width="1648" alt="Screenshot 2020-05-17 at 12 45 55" src="https://user-images.githubusercontent.com/13700/82143513-677e1f80-983c-11ea-9481-a4e563431b10.png">

**Comment by remy** [comment]
This is live now, and I've also added a zoom menu item (top right) which will launch into fullscreen and from there you can ctrl + to zoom the whole page (along with the tilemap making full use of the horizontal space).
