### ISSUE TITLE
Request: choose save location for sheets

### ISSUE THREAD

**Issue by celeritydesign** [remy/zx-tools#16]
A minor request, but it would help workflow if we could choose the file location when saving spritesheets and tilemaps.  On Windows Chrome currently, we have to type out a filename each time, then move the file from Downloads into our working folder.  It would be nicer to just have a standard file dialogue, so we could click on the previous file in the correct location and overwrite without typing.

Thanks!

**Comment by remy** [comment]
This is a (standard security) constraint of the browser.

It's definitely frustrating that the browser doesn't remember the last saved location, but my code has no way to control the file location you save to I'm afraid.
