### ISSUE TITLE
Sprite tool, cut & paste seems to be broke on latest version.

### ISSUE THREAD

**Issue by Andy1966uk** [remy/zx-tools#18]
Hi Remy, appears the latest version of the online Sprite tool, the cut and paste sprite functionality has stopped working... thx

**Comment by remy** [comment]
Bah, right-o on it.

8x8 landed but I'm now fire testing it with my own game and I can see somethings that it could really benefit from.

Still - I'll fix the copy & paste.

**Comment by remy** [comment]
Fix going live now.

**Comment by Andy1966uk** [comment]
perfect, thanks works now...
