### ISSUE TITLE
Favicon for the Sprite tools

### ISSUE THREAD

**Issue by celeritydesign** [remy/zx-tools#23]
How about a favicon for the tool, so we can easily find it amongst dozens of browser tabs?
I've attached a couple of suggestions. I would have included Horace but don't imagine you fancy legal hassles ;-) .

(this is a tongue in cheek request, feel free to close and ignore ;-)  )

![favicon_manic_2](https://user-images.githubusercontent.com/285563/83016070-4d50f800-a019-11ea-85d9-fbc1c56fa6db.png)
![favicon_manic_1](https://user-images.githubusercontent.com/285563/83016077-4de98e80-a019-11ea-92c7-d4ecd78bdad7.png)
![favicon_manic_3](https://user-images.githubusercontent.com/285563/83039340-f3aaf680-a035-11ea-8633-555aae7c1c9a.png)

**Comment by remy** [comment]
😄 I like it - I'll get one up on the next release 👍
