### ISSUE TITLE
SCR to PNG produces garbled output

### ISSUE THREAD

**Issue by pleumann** [remy/zx-tools#24]
I just tried the online converter with some .scr files I needed as .png. The files were all created on the Next using SAVE "..." SCREEN$ and then copied from the SD card to my Mac. Results were garbled, but all in the same way. Is it possible the converter cannot handle the 128 bytes +3DOS header that is included in each disk file created using the BASIC SAVE command? Fix would be easy - just strip the first 128 bytes if the total file length is 6912+128 bytes.

**Comment by remy** [comment]
Ah, good catch - you're right, the scr to png isn't allowing for the +3dos header. 

I'll get that fixed and post here when it's live (it's a simple fix as you suggested).

**Comment by pleumann** [comment]
Great! Looking forward to the new version. In the meantime "tail -c 6912" is my friend.

**Comment by remy** [comment]
Fix going live now - thanks again.

**Comment by pleumann** [comment]
Works perfectly now, thanks for fixing it!
