### ISSUE TITLE
Image Importer not working

### ISSUE THREAD

**Issue by Duefectu** [remy/zx-tools#27]
In EDGE Chromium, the option to import from PNG to Sprite didn't work.
The png is shown, but when clic on the "Copy to sprite", not copy to sprite and image resets to end if the image position.
With Chrome works well!

**Comment by remy** [comment]
I think this is a new bug affecting all browsers, I was trying to import the other day and noticed a similar issue (just put it down to my random browser state).

**Comment by remy** [comment]
Got it. Fixed and release is going up now (you might have to hit refresh a few times for it to land).

**Comment by Duefectu** [comment]
Now it works!
