### ISSUE TITLE
Upload map not working on EDGE Chromium

### ISSUE THREAD

**Issue by Duefectu** [remy/zx-tools#28]
With EDGE Chromium when click on "Upload map" nothing happens.
In Chrome works.

Thanks for your time!

**Comment by remy** [comment]
Does drag and drop work if you drop into the main map area?

**Comment by Duefectu** [comment]
Drag & drop works well!
Select file for background works!
Load debug sprites works!
The only options that not work is the button "Upload map". No errors on console.

**Comment by remy** [comment]
Okay, cheers. Looks like you've got a work around for the moment - and I'll
get that particular button fixed.

**Comment by Duefectu** [comment]
It works!

Thank you!
