### ISSUE TITLE
Tilemap index tooltips are incorrect for 8px tiles

### ISSUE THREAD

**Issue by celeritydesign** [remy/zx-tools#30]
When in 8px tilemap mode, the tooltip (hover title text) showing each block of four tiles is seemingly stuck in 16px numbering mode.
It would be more intuitive I think to multiply by 4, so the last tile shows as index 252, or perhaps a range, "252-255".  Even better would be to have each tile have four tooltips showing the exact index, so the very last tile quadrant would show 255.

Note, this is more obviously a bug when you enable "show index overlay" as then the (correct) overlays in the main tilemap do not match the tooltips.

**Comment by remy** [comment]
Can you grab me a screenshot of where you're looking? (it helps me visualise the problem better) - thanks

**Comment by celeritydesign** [comment]
Sorry, please see below. The selected block of four 8x8 tiles shows a tooltip for index 51 - but when I paste into the tilemap it is index 204.  A quick fix would be just to change the tooltip to show "{index * 4} to {(index * 4) + 3)" which in this case would show "204 to 207" when in 8px mode.
![image](https://user-images.githubusercontent.com/285563/92642822-b151b080-f2d8-11ea-867c-246f48e3753e.png)

**Comment by remy** [comment]
Ah, got you 👍 

Yeah, I suspect I'll just drop those tool tips entirely - since it's repeated at the top (next to the selected sprite) and *that* does work.

Thanks - will fix/sort out!
