### ISSUE TITLE
8px sprite paste doesn't select correct sprite

### ISSUE THREAD

**Issue by celeritydesign** [remy/zx-tools#31]
In 8px mode, if you copy/paste a sprite, the currently selected sprite should be the one you just pasted, like in 16px mode.
eg:

![image](https://user-images.githubusercontent.com/285563/93003086-9f1f7e80-f533-11ea-9a20-678b3599bb21.png)

Inthe above screen shot I have pasted from the top left position to the bottom right. But if I then start editing I will actually still be editing the original (top left) not the newly pasted one.

**Comment by remy** [comment]
Oh, so the selection changes when the sprite has changed. Got it, should be simple(ish!) to fix.

(Thanks for filling these - they're little annoyance that I've lived with, but fixing them makes for a better UX 👍)

**Comment by remy** [comment]
A bunch of the issues you raised have been fixed (and the issues auto-marked as closed as the commits are going live).

You'll need to do a refresh, but you should find any issue that was marked as closed is now resolved. If they're not, do let me know, I'll reopen and look further into the source.

Thanks again.
