### ISSUE TITLE
8px sprite mode Undo Tool bug

### ISSUE THREAD

**Issue by celeritydesign** [remy/zx-tools#34]
Undo has weird behaviour for me when in 8px sprite mode.
For example, in this screenshot I've painted some random red pixels in one operation with the pen tool, so clicking Undo should remove them:

![image](https://user-images.githubusercontent.com/285563/93003374-15bd7b80-f536-11ea-80af-d3ae160903a6.png)

What actually happens though, is that the Undo doesn't remove the drawing operation, instead it seemingly wipes the sprites in my current block - see higlighted area below:

![image](https://user-images.githubusercontent.com/285563/93003416-69c86000-f536-11ea-99ce-6aebd2a38b47.png)

 ...but, if I click those sprites individually, they are restored.  I can then sometimes click Undo again and it works as exppected, but other times it does nothing.

**Comment by remy** [comment]
Seen the same thing. It's a bug in the display rather than undo.
