### ISSUE TITLE
Feature request: Sprite animation preview

### ISSUE THREAD

**Issue by celeritydesign** [remy/zx-tools#35]
It would be awesome if we could preview what our sprite frames look like when animating.
The UI would, I guess, allow you to set:

-  a start and end index for the frames
- loop or "bounce" when end frame is reached
- delay between frames
- background colour for transparency mask (note this would be handy as a preview even for a single frame)
- (optional phase 2 enhancement) allow the preview sprite to be variously scaled, for people who want to use that feature in their game.

Ideally, this would be implemented on the same tab as the sprite editor, so pixel edits can be seen in realtime.

Thanks as always!

**Comment by remy** [comment]
Most of this is straight forward. What would make this really useful is being able to support composite sprites...

Anyway, all the items you've listed are going live now 👍

**Comment by celeritydesign** [comment]
Wow, that was fast!
The problem I have now is that I have to learn how to animate...

Many thanks for rolling this out, it's going to be massively helpful to the community.
By the way, the "Scale" options don't show for me in the dropdown until I click them:

![image](https://user-images.githubusercontent.com/285563/93720751-f43a4080-fb82-11ea-83ad-04ab0c881e71.png)

And yes, composite sprite suppprt would be amazing. That could be a tricky UI though. I guess it would look like the Tilemap tab, but I don't know enough about how the Next handles them to work out what options are needed.  Maybe ask the person who made a Mortal Kombat prototype for his spritesheet, as that would be a good test case.

**Comment by remy** [comment]
Yeah, it turned out pretty straight forward. Most of the code was wiring the controls to the code (and working out the "saw wave" algo for the bounce effect).

I'm just pushing up a small tweak that should fix the dropdown text colour. I'm on a mac so I don't get that effect, but I'll bust out the windows machine too just to be sure. 👍
