### ISSUE TITLE
Sprite editor copy and paste

### ISSUE THREAD

**Issue by NealeTools** [remy/zx-tools#48]
Hi Remy, any chance you would be able to add shortcuts for copy/paste sprites? Even bette if there was a way to move multiple sprites (without shortcut keys) to a different location in the sprite sheet. Thanks!

**Comment by remy** [comment]
I'm not quite sure about the UX on the interface to do that well (I've got some ideas, but they're not totally straight forward).

Can I ask: what's your intended workflow? Do you need to as a one off more a block of sprites around, or are you finding you're doing this often?

If it's the former, there's a workflow for this, but I'll let you reply first.

**Comment by NealeTools** [comment]
I've needed to do this a couple of times recently when realising I needed more animation frames. It is tedious to manually select each sprite, navigate to copy button, select destination, navigate to paste button. Just Copy/Paste short cut keys would help immensely if you can't think of a simple UI update.

**Comment by remy** [comment]
Oh sod, I completely missed that I had even implemented the copy and paste functionality! Sure, so a starting point is adding keyboard shortcuts - I completely missed adding support for that 🤦 .

Okay, _that_ is easy.

Would it help you also to add a swap sprite keyboard shortcut? That should be easy to add to and might make move stuff around a little quicker too (basically shortcuts with no UI tend to be a lot easier as it's mostly focused in code and not UX).

**Comment by NealeTools** [comment]
Hmmm.. I'm not sure. I personally find the swap function in the palette tool rather confusing to use. Copy/paste of the colour from one location to another selected location would be more useful to me. For example, the other day I needed to duplicate a number of colours in the palette, but I couldn't find any way to do that. In the end I manually edited the palette data. Copy/Paste would enable this pretty easily - but of course, I am not the one coding this! I wouldn't have a clue where to start, and really appreciate these tools you have made.

**Comment by remy** [comment]
Patch going live right now that adds copy and paste keyboard support on the sprite panel (copies the entire sprite and pastes to a the new location) - note that this only works within the session and can't paste across windows (🤔 there's an idea though…)

**Comment by NealeTools** [comment]
I like it! 👍
