### ISSUE TITLE
Sprite editor: Bounce (doesn't bounce)

### ISSUE THREAD

**Issue by NealeTools** [remy/zx-tools#51]
Hi Remy, I noticed that there is no difference in the animation preview between the Loop and Bounce options. Tested on macOS Safari and Chrome.

Bounce option still loops up/up/up: 1 > 8, 1 > 8 etc
Rather than the required up/down/up: 1 > 8 > 1 > 8

If this can be fixed, that would be great! Ta!

**Comment by remy** [comment]
do you have a sample spr file I can use to test with?

**Comment by NealeTools** [comment]
https://www.dropbox.com/s/g0q6vlcey9svh28/TEST.spr?dl=0

**Comment by remy** [comment]
Fix going live now 👍
