### ISSUE TITLE
.spr upload problem

### ISSUE THREAD

**Issue by neosquid** [remy/zx-tools#52]
Hello, I made a 64 sprite 4bit image patterns with the online sprite editor and saved it as an .spr file. 
I then cleared my sprites by selecting 'new sprite sheet', and attempted to upload my saved .spr file back into the sprite editor - It only inserted 4 of my 64 saved sprites.

**Comment by remy** [comment]
Ah! Cool - do let me know if you spot any issues - 4bit sprites was the last sprite based change and I'm not sure how firetested it is. It certainly worked for my own tests, but it's usually live usage that does the trick.
