### ISSUE TITLE
Priority colours in palettes

### ISSUE THREAD

**Issue by NealeTools** [remy/zx-tools#53]
Hi Remy, this is more of a question that an issue.

I noticed that in the SPRITE palette tools, there is a tick box for "has priority". I assume this make an index appear in front of other colours (even if present on a background layer).

My question is: Do you know if this functionality is working for Palettes loaded into SPRITEs or LAYERs in NextBASIC?
I added a priority tick box to a colour index, but it didn't change the codes of the "Manual edit" window. Should it do so?

<img width="177" alt="image" src="https://user-images.githubusercontent.com/19664927/131876417-80e77321-882a-40c1-9e13-0cbcad273431.png">

**Comment by remy** [comment]
You'll need to check the manual to be certain, but IIRC, priority works in layers so the ink sits above the sprite. I've got a feeling someone told me priority ink doesn't apply to sprite palettes - but I'm not 100% certain of it.
