### ISSUE TITLE
Tilemap Default Tile

### ISSUE THREAD

**Issue by robgmoran** [remy/zx-tools#54]
Would it be possible to update the Tilemap screen to enable a default tile to be selected or to fill the tilemap with a specific tile. Currently tile 63 is used which requires all tiles to be exported.

**Comment by remy** [comment]
If you press the "R" key when you're on the tilemap you'll be prompted to replace all tiles with a matching ID with a new ID. i.e. you can change all instances of tile 63 with tile 0. 

I think this lets you work around your requirement.
