### ISSUE TITLE
Option to import PNG into 8x8 sprites

### ISSUE THREAD

**Issue by robsoft** [remy/zx-tools#6]
Apologies if there's a good reason not to do this, or if it's already there and I'm being thick... it would be useful to be able to import a PNG file into 8x8 sprites as well as the current (and very useful) 16x16 process.

**Comment by remy** [comment]
Yep, high on my list, particularly for 8px tile maps.

I just want to make sure I understand how they work (in the Next) before planning the code. From what I've seen, is that the sprite needs to wrap on the first 16x8 rows of the sprite sheet. 

I'll make this the next feature in the tool, but quickly after will need to be the 8x8 based tile maps.

**Comment by remy** [comment]
The maths for this was pretty bonkers, but this now live and part of the PNG import tool.

This is the transform for the pixel index from the regular png to the 8x8 zx spectrum sprite layout:

```
ptr = (112 * Math.floor(i / 128)) + (8 * Math.floor(i / 64)) + (16 * Math.floor((i % 64) / 8)) + (i % 8)
```
