### ISSUE TITLE
Image and font conversion: Preview Spectrum Next formats (.NXI, .SL2, .SLR): Please add Export as BMP

### ISSUE THREAD

**Issue by Luzie67** [remy/zx-tools#69]
Hello,

maybe you could add "Export as BMP" to "Image and font conversion: Preview Spectrum Next formats (.NXI, .SL2, .SLR)" ?

Thank you!

**Comment by remy** [comment]
Sorry, a year later, but did you know you can right click the image and save it?

**Comment by Luzie67** [comment]
> Sorry, a year later, but did you know you can right click the image and save it?

OK Thank you. That way I can only save to .PNG-Format, but it should be really no problem to convert the .PNG to .BMP.

For me, you can close this Issue.
