### ISSUE TITLE
4 bit sprites count

### ISSUE THREAD

**Issue by vito-Z80** [remy/zx-tools#71]
8 bit sprites have 64 patterns. Ok.
4 bit sprites have 128 patterns - visible for edit only 64 items. In the saved 16kb, the second half of the binary is filled with zeros.

**Comment by vito-Z80** [comment]
FPGA holds 16kb of sprites.
64 sprites 8bpp (256 * 64 = 16384)
128 sprites 4bpp (128 * 128 = 16384)
Yes, for 16 colors you can have 128 16x16 sprite templates and also 512 8x8 tile templates

**Comment by ljg701** [comment]
For 4 bit sprites I'm happy if you could just output the file as 8192 bytes rather than 16384, the best solution would be if you could edit edit all 128 4bit patterns though.

**Comment by ljg701** [comment]
This seems to be fixed now (8 bit spr files are only 8192 bytes in length)
